### ISSUE TITLE
testplan agreed upon for 2.7.1 + make visible for community

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_cloud#23]
original issue (closeed, wrong org) 

https://github.com/threefoldtech/home/issues/1040

kds input; - 
|we are working to do the final tests on 2.7 but as part of this process we need to agree on scope of testing more formally

## TODO

- [ ] put in cloud wiki the link to the testplan and how to look at result
- [ ] do a review of the testplan with e.g. Kristof, ...
- [ ] look at test results, how far did we get and see if we can do all in timing of roadmap
- [ ] make sure test plan can be consulted by everyone (if needed create generic test user for read only access)

Weynand input
Testplan to be create and published (also in testlodge)

Trasafer testplan knowledge to the wiki - make the wiki the master source of test plan information and position testlodge as the execution engine of it.
- [ ] create all testplan content in wikis.  extract existing information from testlodge
- [ ] extract tesplan logic to testlodge (automation?)  If nto possible cancel testlodge.
- [ ] make wikii version the master
- [ ] if testlodge extraction is not possible -> use github issues + projects as testing tools.

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/75
